[project]
name = "corr2p"
version = "0.1.0"
description = "Compute p-value from Pearson correlation coefficient."
requires-python = "==3.13.*"
dependencies = [
    "click==8.3.1",
    "scipy==1.16.3",
]

[project.scripts]
corr2p = "main:main"

[build-system]
requires = ["setuptools==70.0.0"]
build-backend = "setuptools.build_meta"