[project]
name = "corr2p"
version = "0.1.0"
description = "Compute p-value from Pearson correlation coefficient."
requires-python = "==3.13.*"
readme = "README.md"
dependencies = [
    "click==8.3.1",
    "scipy==1.16.3",
]

[project.scripts]
corr2p = "main:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pytest==9.0.2",
]
